import type { Builder } from '@/types/domain';

export const CURRENT_BUILDERS_LAUNCH_STATE: Builder[] = [
  {
    id: 'launch-state-builder-1',
    displayName: 'Amara Chukwu',
    avatarUrl: null,
    role: 'Frontend Builder',
    skills: ['React', 'TypeScript', 'Design Systems'],
    profileHref: '#',
    profileSummary:
      'Builds fast, accessible interfaces and documents the process as she goes.',
    featuredProject: { name: 'Open component library for fintech teams', thumbnailUrl: null },
    socialLinks: [{ label: 'GitHub', url: '#' }],
  },
  {
    id: 'launch-state-builder-2',
    displayName: 'Kenji Osei',
    avatarUrl: null,
    role: 'Backend Builder',
    skills: ['Node.js', 'PostgreSQL', 'System Design'],
    profileHref: '#',
    profileSummary: 'Ships infrastructure most people never see, and writes about why it matters.',
    featuredProject: { name: 'Realtime event pipeline for logistics tracking', thumbnailUrl: null },
    socialLinks: [{ label: 'GitHub', url: '#' }],
  },
  {
    id: 'launch-state-builder-3',
    displayName: 'Fatima Al-Rashid',
    avatarUrl: null,
    role: 'Product Designer',
    skills: ['Figma', 'Prototyping', 'Design Systems'],
    profileHref: '#',
    profileSummary: 'Designs interfaces that hold up under real use, not just in a portfolio.',
    featuredProject: { name: 'Onboarding redesign for a healthcare app', thumbnailUrl: null },
    socialLinks: [{ label: 'Portfolio', url: '#' }],
  },
  {
    id: 'launch-state-builder-4',
    displayName: 'Daniel Mensah',
    avatarUrl: null,
    role: 'Mobile Builder',
    skills: ['Swift', 'Kotlin', 'React Native'],
    profileHref: '#',
    profileSummary: 'Cross-platform builder focused on performance and small details.',
    featuredProject: { name: 'Offline-first budgeting app', thumbnailUrl: null },
    socialLinks: [{ label: 'GitHub', url: '#' }],
  },
  {
    id: 'launch-state-builder-5',
    displayName: 'Zara Ibrahim',
    avatarUrl: null,
    role: 'Data Builder',
    skills: ['Python', 'Machine Learning', 'Data Pipelines'],
    profileHref: '#',
    profileSummary: 'Turns messy data into tools other builders actually want to use.',
    featuredProject: { name: 'Open dataset of regional startup activity', thumbnailUrl: null },
    socialLinks: [{ label: 'GitHub', url: '#' }],
  },
  {
    id: 'launch-state-builder-6',
    displayName: 'Tomás Silva',
    avatarUrl: null,
    role: 'Full-Stack Builder',
    skills: ['Next.js', 'Supabase', 'TypeScript'],
    profileHref: '#',
    profileSummary: 'Prefers shipping small, working things over planning big, unfinished ones.',
    featuredProject: { name: 'Community events platform for local meetups', thumbnailUrl: null },
    socialLinks: [{ label: 'GitHub', url: '#' }],
  },
];
